Vagrant.configure("2") do |config|
    # Define web01 VM with a specific IP
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/bionic64"
      web01.vm.network "private_network", ip: "192.168.56.41"
      web01.vm.hostname = "web01"
    end
  
    # Define web02 VM with a specific IP
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/bionic64"
      web02.vm.network "private_network", ip: "192.168.56.42"
      web02.vm.hostname = "web02"
    end
  
    # Define db01 VM with a specific IP
    config.vm.define "db01" do |db01|
      db01.vm.box = "centos/7"
      db01.vm.network "private_network", ip: "192.168.56.43"
      db01.vm.hostname = "db01"
  
      # Provisioning for db01 using a shell script
      db01.vm.provision "shell", inline: <<-SHELL
        # Your provisioning commands for db01 go here
        # For example, you can install software, configure the system, etc.
        yum install -y wget unzip mariadb-server
        systemctl start mariadb
        system enable mariadb
      SHELL
    end
  end
  